### ISSUE TITLE
Install deletefiles in 

### ISSUE THREAD

**Issue by morange** [fnagel/deletefiles#10]
Hej Felix,
i tried to install your extension deletefiles. I'm tried at Alfahosting PHP8.1 and 8.0 and became the following error message in my Composer installation (TYPO3 v11, PHP 8.1): 
`[InvalidArgumentException]                                                                                                     
  Package felixnagel/deletefiles has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version:  
    - felixnagel/deletefiles requires php >=7.4,<8.2 which does not match your installed version 8.2.7.                          
    - felixnagel/deletefiles requires typo3/cms-core >=10.4.0,<=11.5.99 but it is not present.`

Do you have an idea, whats wrong?

Best greetings

**Comment by fnagel** [comment]
It looks like you are running PHP v8.2.7. That looks like the issue here.

Maybe you need to prefix the composer command in order to have the proper PHP version when using the CLI?

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by fnagel** [comment]
Closed as no feedback was given. Please reopen or create a new ticket if needed.
