### ISSUE TITLE
Support of PHP 7.3.x

### ISSUE THREAD

**Issue by bh-teufels** [fnagel/deletefiles#3]
is there a plan if / when PHP 7.3.x (7.3.5) will be supported?
Thank you

**Comment by fnagel** [comment]
Did you experience issues? Or can you confirm its working?

**Comment by bh-teufels** [comment]
i tried to install it over composer but get the error `felixnagel/deletefiles 1.0.3 requires php >=7.0,<7.3 -> your PHP version (7.3.5) does not satisfy that requirement.`

i did not tried to change the requirement to >=7.0,<=7.3.99

**Comment by fnagel** [comment]
Yeah, I always configure the dependency constraints for what I've tested so far.

Would you mind changing the constraints and test a little?

**Comment by bh-teufels** [comment]
yes i will test it in the next weeks

will you make a custom branch on which the dependency are set up and that i can use?

**Comment by haug-den-lucas** [comment]
> 
> 
> yes i will test it in the next weeks
> 
> will you make a custom branch on which the dependency are set up and that i can use?

Did you already test if it works with PHP 7.3?

**Comment by bh-teufels** [comment]
yes it worked for me with Typo3 9.5.14 and PHP 7.3.16

**Comment by fnagel** [comment]
> yes it worked for me with Typo3 9.5.14 and PHP 7.3.16

Nice. Thanks for the feedback!


@Ich5003 Any chance to get another review on this? `master` branch is now PHP 7.3 compatible!

**Comment by haug-den-lucas** [comment]
Thanks for your answers.
Later this day I will copy my current Typo3 installation into a a test environment and will recheck the compatibility with PHP 7.3

**Comment by haug-den-lucas** [comment]
So, application works with php7.3
But I think I misunderstood how it works. I thought the application only deletes files, which are older than a specific date AND aren't used on any website anymore.
Maybe this should be mentioned anywhere.

Luckily I did this in a test environment :)

**Comment by fnagel** [comment]
@Ich5003 Thanks for the feedback and the testing in general! 

> But I think I misunderstood how it works. I thought the application only deletes files, which are older than a specific date AND aren't used on any website anymore.

Ohhh, I'm glad you didn't erased files on PROD!

This extension was created long before FAL was a thing, so the docs might be a little ambiguous. There is support for FAL nowadays but only that EXT:deletefiles will remove a file from the FAL index. 

Checking if a file is still in use and not deleting it is a feature request, see #1 

> Maybe this should be mentioned anywhere.

Yeah, you're right. Adding one or two sentence in order to make thing more clear wouldn't hurt. Will be included in next release.
