### ISSUE TITLE
Function create_function() is deprecated

### ISSUE THREAD

**Issue by alexanderkrusche** [fnagel/deletefiles#5]
Hi Felix,

within our TYPO3 project we use TYPO3 10.4.15 with PHP 7.4.15. 

Unfortunately after we configure the planner task and run we get 
"PHP Runtime Deprecation Notice: Function create_function() is deprecated in .../typo3conf/ext/deletefiles/Classes/Task/DeleteFilesTask.php line 351"

We would be happy if that could be resolved. Many Thanks!

**Comment by fnagel** [comment]
Sorry for the late response. 

Yes, that should be replaced! Do you want to create a PR? Otherwise I will remove it in my next maintenance release.

**Comment by fnagel** [comment]
Fixed in fe84460781bee9459867b7714a2ddc2122f61308 

A release will follow soon!

**Comment by fnagel** [comment]
Fixed in 1.2.0
