### ISSUE TITLE
Error while opening scheduler BE module

### ISSUE THREAD

**Issue by froemken** [fnagel/deletefiles#7]
Hello Frank,

TYPO3: 10.4
PHP: 7.3

Opening the scheduler BE module results in following error message:

```
Oops, an error occurred!
syntax error, unexpected 'bool' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)
```

Your extensions seems to have support for TYPO3 10.5 and PHP >= 7.2. So it matches my environment.

You're using typed properties in `DeleteFilesTask` which are supported first in PHP 7.4.

Have a nice start into the upcoming weekend

Stefan

**Comment by fnagel** [comment]
Hey @froemken, you are absolutely right, version 1.2.0 should have not been released for PHP >= 7.2 as it has been. I've been using rector and it seems my configuration is faulty. 

I will release a new 1.2.1 version with proper dependencies for PHP 7.4 only. Reverting those PHP >= 7.2  changes seems unneeded work. PHP 7 is almost dead and no new features or bugfixes haven been added, so downgrading to 1.1.x should be fine. Any objections?

Thanks a lot for reporting!

**Comment by froemken** [comment]
Hi @fnagel 

setting proper PHP requirements is absolutely OK for me.

Nice greetings

Stefan

**Comment by fnagel** [comment]
Hey Stefan, thanks for the fast response and again, your contribution is highly appreciated :-)

New TER release is on its way...
