### ISSUE TITLE
Support for TYPO3 v12

### ISSUE THREAD

**Issue by fritzdacat** [fnagel/deletefiles#8]
Hello, are there any plans for TYPO3 12 support?

**Comment by fnagel** [comment]
Release is planned for end of this summer. Hopefully. Any help is appreciated!

**Comment by fnagel** [comment]
WIP branch: https://github.com/fnagel/deletefiles/tree/typo3-12

**Comment by fnagel** [comment]
Extension should be ready. Feedback would be appreciated, please see WIP branch!

**Comment by fnagel** [comment]
Version 1.3.0 with support for TYPO3 12 has been released: https://github.com/fnagel/deletefiles/releases/tag/1.3.0
